export interface ILead {
  account: string
  affilate: null
  buyer: string
  click_id: string
  comment: string
  lead_password: string
  country: string
  country_code: string
  created_at: string
  current_status: number
  domain: string
  email: string
  first_name: string
  id: string
  ip: number
  language: string
  last_name: string
  offer: string
  param_1: string
  param_2: string
  param_3: string
  param_4: string
  param_5: string
  param_6: string
  param_7: string
  param_8: string
  param_9: string
  param_10: string
  param_11: string
  param_12: string
  param_13: string
  param_14: string
  param_15: string
  phone: string
  phone_code: string
  status: string
  updated_at: string
}
